export const projects = [
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/mates.png",
    name: "Donors",
    ext: "jsx",
    lang: "js",
    git: "https://youtu.be/Zm4ptkIXlTA",
    live: "http://mw.mait.ac.in/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/background.gif",
    name: "FlyBuy",
    ext: "vue",
    lang: "py,js",
    git: "https://github.com/smrnjeet222/FlyBuy-Backend-Django",
    live: "https://github.com/smrnjeet222/FlyBuy-Backend-Django",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/blog.jpg",
    name: "Django Blog",
    ext: "py",
    lang: "py",
    git: "https://github.com/smrnjeet222/Django_Blog",
    live: "https://smrnjeetblogs.herokuapp.com/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/Rock-Paper-Scissors/demo.jpg",
    name: "Multiplayer R.P.S",
    ext: "py",
    lang: "py,games",
    git: "https://github.com/smrnjeet222/Python_Apps/tree/master/Rock-Paper-Scissors",
    live: "https://github.com/smrnjeet222/Python_Apps/tree/master/Rock-Paper-Scissors",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/Snake/Extras/play.png",
    name: "Snake Game",
    ext: "py",
    lang: "py,games",
    git: "https://github.com/smrnjeet222/Python_Apps/tree/master/Snake",
    live: "https://github.com/smrnjeet222/Python_Apps/tree/master/Snake",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/portfolio.png",
    name: "Old Portfolio",
    ext: "js",
    lang: "js",
    git: "https://github.com/smrnjeet222/Portfolio",
    live: "https://smrnjeet222.github.io/Portfolio/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/surepass/bgvAll.png",
    name: "Surepass",
    ext: "jsx",
    lang: "js",
    git: "https://github.com/smrnjeet222/Surepass/blob/main/README.md",
    live: "https://github.com/smrnjeet222/Surepass/blob/main/README.md",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/SudokuSolver/2.png",
    name: "Sudoku Solver",
    ext: "py",
    lang: "py,games",
    git: "https://github.com/smrnjeet222/Python_Apps/tree/master/SudokuSolver",
    live: "https://github.com/smrnjeet222/Python_Apps/tree/master/SudokuSolver",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/newslaundry.png",
    name: "Newslaundry",
    ext: "jsx",
    lang: "js",
    git: "https://github.com/smrnjeet222/newslaundry",
    live: "https://smrnjeet222.github.io/newslaundry/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/recipe.jpg",
    name: "Recipe App",
    ext: "jsx",
    lang: "js",
    git: "https://github.com/smrnjeet222/recipe-app",
    live: "https://smrnjeet222.github.io/recipe-app/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/bubblesort.png",
    name: "Visualisations",
    ext: "js",
    lang: "js",
    git: "https://editor.p5js.org/smrnjeet222/collections/fvtHa48dt",
    live: "https://editor.p5js.org/smrnjeet222/sketches/T0o5woDT5",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/covid.png",
    name: "Python Apps",
    ext: "py",
    lang: "py",
    git: "https://github.com/smrnjeet222/Python_Apps",
    live: "https://github.com/smrnjeet222/Python_Apps",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/background.gif",
    name: "DumpBox",
    ext: "jsx",
    lang: "js",
    git: "https://github.com/smrnjeet222/DropBox-Clone",
    live: "https://github.com/smrnjeet222/DropBox-Clone",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/pg.png",
    name: "Pico-Gram",
    ext: "jsx",
    lang: "js",
    git: "https://github.com/smrnjeet222/PicoGram",
    live: "https://smrnjeet-picogram.web.app/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/BLENDER/master/Abstract_Design/Abstract.png",
    name: "Blender",
    ext: "models",
    lang: "games",
    git: "https://github.com/smrnjeet222/BLENDER",
    live: "https://smrnjeet222.github.io/BLENDER/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/worldRanks.png",
    name: "WorldRanks",
    ext: "tsx",
    lang: "js",
    git: "https://github.com/smrnjeet222/WorldRanks",
    live: "https://world-ranks-smrnjeet222.vercel.app/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/Unity_Gamedevelopment/master/MYGAME.png",
    name: "Unity Games",
    ext: "c#",
    lang: "games",
    git: "https://github.com/smrnjeet222/Unity_Gamedevelopment",
    live: "https://smrnjeet-22.itch.io/",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/background.gif",
    name: "NoJs-TicTacToe",
    ext: "css",
    lang: "js",
    git: "https://github.com/smrnjeet222/noJs-TicTacToe",
    live: "https://codepen.io/smrnjeet222/full/gOLjOXM",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Automail.png",
    name: "AutoMail",
    ext: "py",
    lang: "py",
    git: "https://github.com/smrnjeet222/AutoMail",
    live: "https://github.com/smrnjeet222/AutoMail",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/Unity_Gamedevelopment/master/FreakyFrog/best.png",
    name: "Freaky Frog",
    ext: "c#",
    lang: "games",
    git: "https://github.com/smrnjeet222/Unity_Gamedevelopment",
    live: "https://smrnjeet-22.itch.io/freaky-frog",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Astar.png",
    name: "A*Pathfinding",
    ext: "py",
    lang: "py",
    git: "https://github.com/smrnjeet222/Python_Apps/tree/master/A-star",
    live: "https://repl.it/@smrnjeet222/Astar#main.py",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/Space-invaders/Sc.jpg",
    name: "Space-invaders",
    ext: "py",
    lang: "py,games",
    git: "https://github.com/smrnjeet222/Python_Apps/tree/master/Space-invaders",
    live: "https://github.com/smrnjeet222/Python_Apps/tree/master/Space-invaders",
  },
  {
    img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Rc.png",
    name: "Ray Casting",
    ext: "js",
    lang: "js",
    git: "https://editor.p5js.org/smrnjeet222/collections/fvtHa48dt",
    live: "https://editor.p5js.org/smrnjeet222/sketches/j06TXs4ZF",
  },
];